### ISSUE TITLE
Add kustomizer

### ISSUE THREAD

**Issue by ajeetsraina** [collabnix/kubetools#125]
Kustomizer is an experimental package manager for distributing Kubernetes configuration as OCI artifacts. It offers commands to publish, fetch, diff, customize, validate, apply and prune Kubernetes resources.

https://github.com/stefanprodan/kustomizer

**Comment by ajeetsraina** [comment]
@apurvabhandari

**Comment by apurvabhandari** [comment]
added kustomizer #125
