### ISSUE TITLE
Add tools in a tabular format

### ISSUE THREAD

**Issue by ajeetraina** [collabnix/kubetools#138]
@apurvabhandari It would be great if we can put these tools into a tabular format based on popularity(GitHub stars)

**Comment by apurvabhandari** [comment]
- Do we need to sort them and then add in the table or one table with the tools ?
- It will be static if we add them in table based on popularity

**Comment by collabnix** [comment]
@apurvabhandari Something like https://github.com/collabnix/docker-community-extensions

**Comment by ajeetraina** [comment]
Looks perfect. Thanks @apurvabhandari
