### ISSUE TITLE
Add scroll-to-top button 

### ISSUE THREAD

**Issue by RajeevDash007** [collabnix/kubetools#187]
assign me this, so that I can add it

**Comment by apurvabhandari** [comment]
@RajeevDash007 Please raise the PR!

**Comment by RajeevDash007** [comment]
alright

**Comment by RajeevDash007** [comment]
@apurvabhandari can you please provide some instruction for contribution in your project, ie. after forking what dependencies or packages we have to setup to get the required output

**Comment by apurvabhandari** [comment]
@RajeevDash007 No dependency!

**Comment by Vaisakh-RS** [comment]
@apurvabhandari is there a guide for contributors or a guide on how to set up?

**Comment by vishalverma9572** [comment]
Sir, I am working on this feature..

**Comment by vishalverma9572** [comment]
![Screenshot 2023-10-04 220953](https://github.com/collabnix/kubetools/assets/129514369/a3459817-48a8-40a1-931d-5c448dc90553)
