### ISSUE TITLE
Dark Theme for the Website

### ISSUE THREAD

**Issue by thanmaisai** [collabnix/kubetools#216]
### info
Adding Dark them to the website using a toggle through we can switch between dark and light themes.

### Steps to reproduce
* Create Dark Theme CSS Styles
* Toggle Switch HTML Element
* JavaScript for Theme Toggling
* Media Queries (Optional)
* Include CSS and JavaScript Files
* Testing

### Expected behavior
A toggle to turn the website dark or light mode.

### Actual behavior
There is no mode for theme in the current website.

**Comment by thanmaisai** [comment]
Note

Please assign me this issue, and do add the labels for the issue/PR raised in order to make it a valuable contribution for hacktoberfest 2023

**Comment by ajeetraina** [comment]
Cc @PascalBourdier

**Comment by apurvabhandari** [comment]
Noted @thanmaisai ! Please raise the PR I will merge with hacktoberfest label.

**Comment by thanmaisai** [comment]
> Noted @thanmaisai ! Please raise the PR I will merge with hacktoberfest label.

Hi @apurvabhandari , I've created a pull request at https://github.com/collabnix/kubetools/pull/217. Please review it and let me know if you need any changes. If everything looks good, please merge it with the "hacktoberfest" label.

**Comment by thanmaisai** [comment]
Hi @apurvabhandari,

Just checking in on my pull request #217. Would appreciate your review. Let me know if any changes are needed.
Thanks!

**Comment by thanmaisai** [comment]
Hi @apurvabhandari,

Just checking in on my pull request https://github.com/collabnix/kubetools/pull/217. Would appreciate your review. Let me know if any changes are needed.
Thanks!

**Comment by apurvabhandari** [comment]
I have merged the code. Please test it once.
