### ISSUE TITLE
`Top Featured Kubernetes Tools(Jan 2024)` links are broken

### ISSUE THREAD

**Issue by morkot** [collabnix/kubetools#266]

**Comment by alwinhb** [comment]
Looks Like kubetools.io isn't available causing this issue!

![image](https://github.com/collabnix/kubetools/assets/90553514/cfceac23-7730-4523-bc37-9de3f388a90f)

@ajeetraina

**Comment by ajeetraina** [comment]
We are working on this issue. Will keep you updated

**Comment by ajeetraina** [comment]
@morkot We have fixed all the links. Thanks for reporting.
