### ISSUE TITLE
Cleanup section of the deployed webpage is not rendering markdown table correctly

### ISSUE THREAD

**Issue by BeardedOwl1357** [collabnix/kubetools#270]
Hi. First, this is a great resource. 

I was looking at the list on your deployed website https://collabnix.github.io/kubetools and found that the `cleanup` section isn't rendering properly however in github documentation, it is rendering fine
Since I didn't see any issue regarding this, I am creating one

Website
<img width="915" alt="image" src="https://github.com/collabnix/kubetools/assets/59707554/faeccfc4-32cd-403c-ba47-d151ad5dc4e2">

Github Documentation
<img width="855" alt="image" src="https://github.com/collabnix/kubetools/assets/59707554/bcc2d8a4-30f2-4fd2-817d-63fabe2f3885">

**Comment by ajeetraina** [comment]
@apurvabhandari Can you please look into this?

**Comment by apurvabhandari** [comment]
Thanks for raising issues. It's now resolved now.
<img width="1003" alt="Screenshot 2024-05-10 at 12 27 31 PM" src="https://github.com/collabnix/kubetools/assets/38501348/09576171-6323-49fb-a857-e05ceeaa261e">
