### ISSUE TITLE
Add SkyPilot

### ISSUE THREAD

**Issue by ajeetraina** [collabnix/kubetools#312]
SkyPilot: Run LLMs, AI, and Batch jobs on any cloud. Get maximum savings, highest GPU availability, and managed execution—all with a simple interface.

https://github.com/skypilot-org/skypilot

**Comment by Harsh-1Byte** [comment]
Hey Maintainer @ajeetraina, @apurvabhandari 
I tried to solve the issue by raising the pr #338 please do check it out :)

**Comment by apurvabhandari** [comment]
https://github.com/collabnix/kubetools/pull/338
