### ISSUE TITLE
add kubed

### ISSUE THREAD

**Issue by ajeetraina** [collabnix/kubetools#313]
Kubed is a rich Kubernetes interface within Emacs. It helps you work with your Kubernetes clusters and deployments with the full power of kubectl, and with the comfort and confidence of an intuitive interactive interface.

https://github.com/eshelyaron/kubed

**Comment by Harsh-1Byte** [comment]
Hi maintainers @apurvabhandari, @ajeetraina,
I have raised a pr #334 which add this tool in the Cluster CLI Tools.

**Comment by apurvabhandari** [comment]
#334
