### ISSUE TITLE
Add Infoscale for kubernetes over storage provider section

### ISSUE THREAD

**Issue by marcelogigliotti** [collabnix/kubetools#321]
Hi there!

I’d like to introduce Veritas Infoscale for Kubernetes Project. I understand it covers a specific and perhaps niche use case of Kubernetes, but I believe it could be helpful to others besides me and my colleagues.

This project is about integrating Veritas InfoScale for Kubernetes, a robust solution to protect and manage critical data and applications in Kubernetes environments. It simplifies the automation of failover and high availability for your applications, bringing InfoScale’s reliability into Kubernetes. The solution has a free version and can be deployed for anyone

If you find this project useful and decide it could be included in a list of recommendations, it would be great to have it mentioned here as well.

Feel free to share your thoughts, especially if you believe the project doesn’t follow conventions. I’m open to constructive criticism!

https://www.veritas.com/availability/infoscale-kubernetes

**Comment by ajeetraina** [comment]
Cc @apurvabhandari

**Comment by marcelogigliotti** [comment]
Thanks,

Please let me know if you have any question or I can provide
more information


Regards

Marcelo Gigliotti

**Comment by Harsh-1Byte** [comment]
Hey @ajeetraina, @apurvabhandari 
Can you please review my PR #327 so I can make it better :)

**Comment by apurvabhandari** [comment]
https://github.com/collabnix/kubetools/pull/327
