### ISSUE TITLE
Add RBAC Wizard

### ISSUE THREAD

**Issue by ajeetraina** [collabnix/kubetools#324]
RBAC Wizard is a tool that helps you visualize and analyze the RBAC configurations of your Kubernetes cluster. It provides a graphical representation of the Kubernetes RBAC objects.

https://github.com/pehlicd/rbac-wizard

**Comment by Harsh-1Byte** [comment]
Hey @ajeetraina 
Can you please review my PR so I can make it better :)

**Comment by apurvabhandari** [comment]
https://github.com/collabnix/kubetools/issues/324
