### ISSUE TITLE
Adding Apache OpenServerless

### ISSUE THREAD

**Issue by d4rkstar** [collabnix/kubetools#343]
Hello @ajeetraina, 

i would like to add to the list Apache OpenServerless in the FaaS section.
OpenServerless is an open source, cloud-agnostic, serverless platform. It offer a complete environment for serverless applications development, based on Kubernetes. With Apache OpenWhisk as its FaaS engine, it provides an unified developer experience with a plethora of services (SQL and noSQL databases, key-value stores, object storage, LLMs services, function schedulers) managed by the platform’s core: the operator, along with tooling (the CLI) to simplify (and interact with) deployments, integrated ide and starter application and optmized runtimes integrated with the staters.

Website: https://openserverless.apache.org
GitHub repo: https://github.com/apache/openserverless

I will add a PR for this. Let me know if there is any other requirements.

**Comment by apurvabhandari** [comment]
#344
