### ISSUE TITLE
Add Kro - Kube Resource Orchestrator

### ISSUE THREAD

**Issue by ajeetraina** [collabnix/kubetools#351]
https://github.com/awslabs/kro

kro (Kube Resource Orchestrator) is an open-source, Kubernetes-native project that allows you to define custom Kubernetes APIs using simple and straightforward configuration. 

With kro, you can easily configure new custom APIs that create a group of Kubernetes objects and the logical operations between them. 

Kro leverages [CEL (Common Expression Language)](https://github.com/google/cel-spec), the same language used by Kubernetes webhooks, for logical operations. Using CEL expressions, you can easily pass values from one object to another and incorporate conditionals into your custom API definitions. Based on the CEL expressions, kro automatically calculates the order in which objects should be created. You can define default values for fields in the API specification, streamlining the process for end users who can then effortlessly invoke these custom APIs to create grouped resources.

**Comment by collabnix** [comment]
Cc @Adesoji1
