### ISSUE TITLE
Unable to edit the page 

### ISSUE THREAD

**Issue by ajeetraina** [collabnix/kubetools#86]
@sharu725 The edit under https://collabnix.github.io/kubetools/ is working fine but not for kubetools.collabnix.com
Can you get it fixed?

**Comment by sharu725** [comment]
I think this is not specific to that link. I see this behavior even here
![image](https://user-images.githubusercontent.com/8033084/156302527-499a2438-b494-42c6-ba2d-5f48cd0a7579.png)

I'm not sure why at this point. I iwill check

**Comment by ajeetraina** [comment]
@sharu725 Any update?

**Comment by sharu725** [comment]
![image](https://user-images.githubusercontent.com/8033084/158604136-597ee5d0-f8e5-4497-bf39-b7844842ac15.png)

Something wrong with how it is hosted. Everything is inside an iframe. That causes this behaviour
